FROM python:3.10

WORKDIR /app

RUN mkdir /app/PostServices
COPY /PostServices/ /app/PostServices/
RUN mkdir /app/Utility_Module
COPY /Utility_Module/ /app/Utility_Module/
RUN mv /app/PostServices/requirements.txt /app
RUN mv /app/PostServices/appsettings.json /app
RUN mv /app/PostServices/app.py /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

EXPOSE 5000

CMD ["flask","run"]

