FROM python:3.10

WORKDIR /app

RUN mkdir /app/UserServices
COPY /UserServices/ /app/UserServices/
RUN mkdir /app/Utility_Module
COPY /Utility_Module/ /app/Utility_Module/
RUN mv /app/UserServices/requirements.txt /app
RUN mv /app/UserServices/appsettings.json /app
RUN mv /app/UserServices/app.py /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

EXPOSE 5000

CMD ["flask","run"]

